services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: python scripts/train.py
    depends_on:
      - mlflow
    profiles:
      - training
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
